server:
  port: 9010

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://43.142.149.214:3306/gulimall_oms
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto